# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'OpenWMS on GitHub'
tagline:          'Users OpenWMS GitHub Page'
description:      'Users GitHub Page'
url:              'https://openwms.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Heiko Scherrer'

#Social Media links (Use complete URL except for email)
dribbble:
email:          'mailto:hscherrer@interface21.io'
facebook:       
flickr:
github:         'https://github.com/openwms'
skype:          'skype:openwms'         
instagram:
pinterest:
linkedin:       'https://www.linkedin.com/in/openwms'
rss:
stackoverflow:  
twitter:        'https://twitter.com/openwms'

# Google Analytics
gahandler: 'UA-83021650-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
